### ISSUE TITLE
로케일 파일을 생성하고 적용했으나 표시되지 않음

### ISSUE THREAD

**Issue by laonmofu** [nekoplanet/misskey-io#1]
### 💡 Summary

locales/index.js 파일 내부 languages에 ko-GS와 ko-NK를 적용했으나, 
다른 버전에서 생성된 파일이라서 그런지는 몰라도 미스키 내부 드롭다운에서 표시되지 않음.

### 🥰 Expected Behavior

설정/일반 언어 드롭다운에 한국어(경상)과 한국어(냥체)도 포함되어야 함

### 🤬 Actual Behavior

내부 드롭다운에는 해당 항목이 표시되지 않음

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Astro-CQM** [comment]
버전명 변경 후 캐시 지우기를 해도 그러던가요

**Comment by laonmofu** [comment]
어라? 버전명 바꾸고 나서는 확인 안 했어서 몰랐는데 변경되어있네요?

문제해결~~ wwww

**Comment by Astro-CQM** [comment]
아니 세상에 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
