### ISSUE TITLE
가져오기/내보내기 기능이 제대로 작동하지 않음

### ISSUE THREAD

**Issue by laonmofu** [nekoplanet/misskey-io#4]
### 💡 Summary

가져오기/내보내기 두 가지 기능이 제대로 작동하지 않습니다.
내보내기를 했을 때에는 파일이 제대로 드라이브에 넣어지지 않으며,
가져오기를 했을 때에 파일 중 일부만 작업이 이행된다고 합니다.

### 🥰 Expected Behavior

내보내기를 동작시켰을 때에 정상적으로 파일이 드라이브에 출력되어야 합니다.
반대로 가져오기를 동작시켰을 때에 파일을 삽입하면 파일에 작성된 모든 유저가 행위에 등록되어야 함

### 🤬 Actual Behavior

실제로는 드라이브에 출력되지 않습니다. 
유저 가져오기를 했을 때 일부만 작동하고 일부는 작동하지 않는다고 함
(n일 전 `@Canon@nekoplanet.xyz`님 제보

### 📝 Steps to Reproduce

1. 설정 / 가져오기와 내보내기
2. 아무 항목이나 내보내기 (알림창은 제대로 작동함)
3. 아무 항목이나 가져오기 (확인하지 않음)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): MacOS 14.1.1(23B81)
* Browser: Arc (Chromium)
* Server URL: satellite.nekoplanet.xyz
* Misskey: 2024.3.1 (io Fork)
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by HotoRas** [comment]
https://satellite.nekoplanet.xyz/notes/9txycu5wn9ca022b

### Expected behavior
팔로우 수가 72임

### Expected buggy behavior
팔로우 수가 특정 수(여기에서는 49)까지 오르고 이후 증가하지 않음

### Actual behavior
초기의 49에서 시간이 지나자 느리게 올라감

### Semi-conclusion
레이트 리밋 문제?

**Comment by laonmofu** [comment]
리밋 문제라면 제 계정에서는 내보내기 기능이 정상적으로 잘 작동해야 합니다 (리미트가 거의 걸려있지 않으므로) 

버그인 것은 명확해 보입니다

**Comment by HotoRas** [comment]
방금도 뜬 거 보니까 리밋 문제나 연합 문제는 아닌 것 같고...
팔로우를 제한한 사용자 중, **받는 측 서버에서 해당 유저가 일정 시간 온라인인 경우** 팔로우 완료 액티비티를 전송하는 것일 가능성에 무게를 두는 게 합리적이라 생각합니다.
이건 Misskey만의 문제도 아닌 게, Mastodon 기반 인스턴스(여기는 아직도 인스턴스라는 단어를 사용하죠)에서도 팔로우 지연 완료 현상이 관측되고 있어서..

**Comment by laonmofu** [comment]
이모지 리스트 출력으로 인한 큐 밀림 현상 확인하고
큐 수동으로 제거해주었습니다.

커모지 리스트 세 번만 출력했으면 서버가 내려갔겠네요.

**Comment by seojangho** [comment]
해당 큐 상황은 https://nekoplanet.xyz/queue/queue/db 에서 확인이 가능했으나, 미스키 제어판에는 표시되지 않아 통상적인 감시 범위에서 벗어나 있었습니다. 장기적으로는 Bull(MQ) 의 큐 상황을 Prometheus/Grafana 등으로 모니터링하고 알람을 받는 시스템을 갖추는게 좋아보입니다.
